### ISSUE TITLE
Feature Request: Number of cases chart inside of each country card

### ISSUE THREAD

**Issue by hugosoftdev** [wobsoriano/covid3d#13]
It would be really nice if in the bottom of the card that gives the country specific information we could see a kind of "mini-chart" with the evolution of the number of cases from the beginning until the day that timeline is showing.

**Comment by Zoleas** [comment]
I am looking into it right now. I may not have finished it today though.
Great little project btw!

**Comment by wobsoriano** [comment]
> I am looking into it right now. I may not have finished it today though.
> Great little project btw!

Thanks. Take your time 😀

**Comment by Zoleas** [comment]
Hello, the graph would be very small if put in the bottom of the card. I tried a design where it is on the right of it. Please tell me what you think of it (the rest of the card is still the original size):
![image](https://user-images.githubusercontent.com/8612822/95617794-4a0c5500-0a6c-11eb-9c89-271a625509dc.png)

**Comment by Zoleas** [comment]
@hugosoftdev @wobsoriano Any feedback on this?

**Comment by wobsoriano** [comment]
> @hugosoftdev @wobsoriano Any feedback on this?

Sorry I missed the notification. I think it looks nice on desktop, not sure on mobile though. Can you send a PR? So we can have a preview of it. Thank you!
