### ISSUE TITLE
Norway Flag Not Load Properly

### ISSUE THREAD

**Issue by dhruvgaloriya** [wobsoriano/covid3d#17]
1. Hi @wobsoriano Norway flag not loading properly as shown in the image
2. Just raise the PR for the same.
![flag](https://user-images.githubusercontent.com/15782988/95019085-19e64000-0681-11eb-987b-91802e857fb4.PNG)

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/covid3d/pull/18
