### ISSUE TITLE
Population of Country shows G instead of B

### ISSUE THREAD

**Issue by adithyapaib** [wobsoriano/covid3d#19]
Populations of India is 1.28B (Billion) But it show 1.28G, Maybe A Typo !

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/covid3d/pull/20

**Comment by puripant** [comment]
I know it's not a typo but SI prefix "G" is not commonly used for population. "M" is used, not short for "Mega" but short for "Million". So I think replacing "G" to "B" for "Billion" as suggested in this issue is a good idea but it's totally up to you.
