### ISSUE TITLE
Wrong country name and data

### ISSUE THREAD

**Issue by juanmarin97** [wobsoriano/covid3d#3]
![imagen](https://user-images.githubusercontent.com/8534968/78116194-91cd6800-73c9-11ea-97fb-10d0011689ae.png) 

This country name is French Guiana not France =>
https://en.wikipedia.org/wiki/French_Guiana

**Comment by sorxrob** [comment]
Thank you. will look into this.

**Comment by real-acmkan** [comment]
It would appear the root issue is the .geojson file, as it also is missing certain countries like Bermuda and Singapore

**Comment by sorxrob** [comment]
> It would appear the root issue is the .geojson file, as it also is missing certain countries like Bermuda and Singapore

Yeah. Would be happy to accept a PR :)

**Comment by real-acmkan** [comment]
Sure, I’ll check it out soon!

**Comment by real-acmkan** [comment]
How would I go about creating a new country on the map?

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/covid3d/pull/21
